dataset:
  train_start_date: 1951-01-01
  train_end_date: 2008-12-31
  validation_start_date: 2009-01-01
  validation_end_date: 2009-12-31 
  test_start_date: 2010-01-01 
  test_end_date: 2014-12-31
  input_path: /mimer/NOBACKUP/groups/mlhighres/projects/HCLIM-emulator/EC-Earth3-Veg/standardized_global
  levels: [100000, 85000, 70000, 50000, 25000, 10000, 5000, 1000]
  input_files: [
     'standardized.global.tas_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.tasmin_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.tasmax_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.sfcWind_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.uas_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.vas_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hurs_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.huss_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.psl_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.clt_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.rsds_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.rlds_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.pr_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.zg_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.prsn_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.prc_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hfss_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.rlus_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.wap_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.sfcWindmax_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.va_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.ua_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hursmax_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hursmin_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.snc_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.ta_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.rlut_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hus_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc',
     'standardized.global.hfls_EC-Earth3-Veg_historical_r1i1p1f1_day_1950-2015_NEA_r360x180.nc'
 ]
  ground_truth_path: /mimer/NOBACKUP/groups/mlhighres/projects/HCLIM-emulator/HCLIM
  ground_truth_files: [
     'standardized.global.tas_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.tasmin_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.tasmax_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.sfcWind_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.uas_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.vas_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.hurs_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.huss_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.psl_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.clt_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.rsds_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.rlds_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
     'standardized.global.pr_remapped_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_day_1951_2014.nc',
 ]
  ground_truth_stats_path: ''
  save_path: ''
  normalize_ground_truth: False # The data on the files is already standardized
  upscale_inputs: True
  static_fields_files: [
    'standardized.remapped.orog_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_fx.nc',
    'scaled.remapped.sftlf_EUR-12_EC-Earth3-Veg_historical_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_fx.nc'
  ]
  interpolation_mode: 'bicubic'
  provide_coordinates: True
  provide_day_of_year: True
  name: clim
  downscaling_idx: [0,1,2,3,4,5,6,7,8,9,10,11,12]
  var_names:
    - tas
    - tasmin
    - tasmax
    - sfcWind
    - uas
    - vas
    - hurs
    - huss
    - psl
    - clt
    - rsds
    - rlds
    - pr
    - zg_1000
    - zg_850
    - zg_700
    - zg_500
    - zg_250
    - zg_100
    - zg_50
    - zg_10
    - prsn
    - prc
    - hfss
    - rlus
    - wap_1000
    - wap_850
    - wap_700
    - wap_500
    - wap_250
    - wap_100
    - wap_50
    - wap_10
    - sfcWindmax
    - va_1000
    - va_850
    - va_700
    - va_500
    - va_250
    - va_100
    - va_50
    - va_10
    - ua_1000
    - ua_850
    - ua_700
    - ua_500
    - ua_250
    - ua_100
    - ua_50
    - ua_10
    - hursmax
    - hursmin
    - snc
    - ta_1000
    - ta_850
    - ta_700
    - ta_500
    - ta_250
    - ta_100
    - ta_50
    - ta_10
    - rlut
    - hus_1000
    - hus_850
    - hus_700
    - hus_500
    - hus_250
    - hus_100
    - hus_50
    - hus_10
    - hfls
  var_units: 
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
    - UNIT
  var_longnames:
    - tas
    - tasmin
    - tasmax
    - sfcWind
    - uas
    - vas
    - hurs
    - huss
    - psl
    - clt
    - rsds
    - rlds
    - pr
    - zg_1000
    - zg_850
    - zg_700
    - zg_500
    - zg_250
    - zg_100
    - zg_50
    - zg_10
    - prsn
    - prc
    - hfss
    - rlus
    - wap_1000
    - wap_850
    - wap_700
    - wap_500
    - wap_250
    - wap_100
    - wap_50
    - wap_10
    - sfcWindmax
    - va_1000
    - va_850
    - va_700
    - va_500
    - va_250
    - va_100
    - va_50
    - va_10
    - ua_1000
    - ua_850
    - ua_700
    - ua_500
    - ua_250
    - ua_100
    - ua_50
    - ua_10
    - hursmax
    - hursmin
    - snc
    - ta_1000
    - ta_850
    - ta_700
    - ta_500
    - ta_250
    - ta_100
    - ta_50
    - ta_10
    - rlut
    - hus_1000
    - hus_850
    - hus_700
    - hus_500
    - hus_250
    - hus_100
    - hus_50
    - hus_10
    - hfls
  num_forcing_features: 0 # TODO: Update this, all inputs that are not in the output is considered forcing
  num_static_features: 6 # TODO: Update this, land-sea mask, orography, etc.
  FULL_GRID_SHAPE: [400, 550] # TODO: Update this
# TODO: NOTE: We don't need a projection here, as the data is already in a regular grid.
# projection:
#   class: LambertConformal
#   kwargs:
#     central_longitude: 15.0
#     central_latitude: 63.3
#     standard_parallels: [63.3, 63.3]
