dataset:
  name: meps_example
  var_names:
    - t_2
  var_units:
    - K
  var_longnames:
    - t_heightAboveGround_2_instant
  num_forcing_features: 1
grid_shape_state: [268, 238]
projection:
  class: LambertConformal
  kwargs:
    central_longitude: 15.0
    central_latitude: 63.3
    standard_parallels: [63.3, 63.3]
